apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: brix-pizza
  namespace: brix
  labels:
    app: brix-pizza
spec:
  selector:
    matchLabels:
      app: brix-pizza
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
